spring:
  application:
    name: rabitmq-provider
  rabbitmq:
    host: 127.0.0.1
    password: guest
    username: guest
    port: 5672
    #消息确认配置项

    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 8107