spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: gateway-service1-route
        uri: lb://gateway-service1
        predicates:
        - Path=/hello1/**
        filters: #解决使用服务名无法访问的问题。
          - StripPrefix=1

      - id: gateway-service2-route
        uri: lb://gateway-service2
        predicates:
        - Path=/hello2/**
        filters: #解决使用服务名无法访问的问题。
            - StripPrefix=1
      discovery:  #开启微服务名字转发   也就是根据服务名去访问不同的项目
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 9094
