spring:
  application:
    name: stream-consumer
  cloud:
    stream:
      binders:
        lagouRabbitBinder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: lagouRabbitBinder
          content-type: application/json
          group: test
          consumer:
            partitioned: true
      instance-count: 2
      instance-index: 0


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 8096