spring:
  application:
    name: ribbon-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: "*"