spring:
  application:
    name: feign-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 8103
  #Dalston及以上的版本中，打开断路器
feign:
  hystrix:
    enabled: true
