spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 8090
zuul:
  routes:
    ribbon:
      path: /api-ribbon/**
      service-id: ribbon-server
    zuul:
      path: /api-zuul/**
      service-id: zuul-service
ribbon:
  ReadTimeout: 120000  #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间